modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="ez_supervisor" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Entity Zoning Supervisor" #mandatory
logoFile="ez_supervisor.png" #optional
authors="EERussianguy" #optional
description='''
A mod to let you control the destiny of mobs.
'''
[[dependencies.ez_supervisor]] #optional
    modId="tfc" #mandatory
    mandatory=false #mandatory
    versionRange="[0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ez_supervisor]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ez_supervisor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
